name: publish helm chart

on:
  push:
    branches:
      - main
      - dev
    paths:
      - charts/waiconv/templates/**
      - charts/waiconv/values.yaml
      - charts/waiconv/Chart.yaml
      - .github/workflows/helm-chart.yaml

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.7.0
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
